#ifndef SOFTWARE_CHALLENGE_2021_CONSTANTS_H
#define SOFTWARE_CHALLENGE_2021_CONSTANTS_H

#define BOARD_SIZE 20
#define BOARD_MAX (BOARD_SIZE - 1)

#define PIECE_SIZE 5
#define PIECE_COUNT 21

#define COLOR_COUNT 4
#define ROTATION_COUNT 4
#define FLIPPED_COUNT 2

#endif
